version: '3'

services:
  modelo:
    build: ./modelo
    volumes:
      - ./modelo:/app
      - ./modelo/modelo_entrenado:/app/modelo_entrenado

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./modelo/modelo_entrenado:/app/modelo_entrenado
    depends_on:
      - modelo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - PORT=80
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:8000